FirstWebApp/Controllers/NhanViensModalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FirstWebApp.Models;

namespace FirstWebApp.Controllers
{
    public class NhanViensModalController : Controller
    {
        private NhanSuEntities db = new NhanSuEntities();

        // GET: NhanViensModal
        public async Task<ActionResult> Index()
        {
            return View(await db.NhanViens.ToListAsync());
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien person = await db.NhanViens.FindAsync(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Details", person);
        }

        // GET: NhanViensModal/Create
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        // POST: NhanViensModal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,hoten,ngaysinh,thuongtru,ngayvaolam,CMND")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.NhanViens.Add(nhanVien);
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("_Create");
        }

        // GET: NhanViensModal/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = await db.NhanViens.FindAsync(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit", nhanVien);
        }

        // POST: NhanViensModal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,hoten,ngaysinh,thuongtru,ngayvaolam,CMND")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhanVien).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return PartialView("_Edit",nhanVien);
        }

        // GET: NhanViensModal/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = await db.NhanViens.FindAsync(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete", nhanVien);
        }

        // POST: NhanViensModal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            NhanVien nhanVien = await db.NhanViens.FindAsync(id);
            db.NhanViens.Remove(nhanVien);
            await db.SaveChangesAsync();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FirstWebApp/Controllers/jsTreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FirstWebApp.Models;
using System.Data.Entity;
using System.Net;

namespace FirstWebApp.Controllers
{
    public class jsTreeController : Controller
    {
        private NhanSuEntities db = new NhanSuEntities();
        // GET: jsTree
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetTreeData()
        {
            
                List<JsTreeModel> nodes = new List<JsTreeModel>();
                //add những node có parentID null
                List<DonVi> dvs = db.DonVis.Where(x => x.parentID == null).ToList();
                foreach (DonVi dv in dvs)
                {
                    JsTreeModel node = new JsTreeModel();
                    node.id = dv.Id;
                    node.text = dv.ten;
                    SetChildren(node);
                    nodes.Add(node);
                }
                //AlreadyPopulated = true;
                return Json(nodes);
            
        }
        public void SetChildren(JsTreeModel node)
        {
            List<DonVi> dvs = db.DonVis.Where(x => x.parentID == node.id).ToList();
            foreach (DonVi dv in dvs)
            {
                JsTreeModel childnode = new JsTreeModel();
                childnode.id = dv.Id;
                childnode.text = dv.ten;
                SetChildren(childnode);
                node.children.Add(childnode);
            }
        }
        [HttpPost]
        public ActionResult DoJsTreeOperation(JsTreeOperationData data)
        {
            switch (data.Operation)
            {
                case JsTreeOperation.CopyNode:
                case JsTreeOperation.CreateNode:
                    //todo: save data
                    DonVi dv = new DonVi();
                    dv.parentID = int.Parse(data.ParentId);
                    dv.ten = data.Text;
                    db.DonVis.Add(dv);
                    db.SaveChanges();
                    return Json(new { id = dv.Id }, JsonRequestBehavior.AllowGet);

                case JsTreeOperation.DeleteNode:
                    //todo: save data
                    int id = int.Parse(data.Id);
                    DonVi donVi = db.DonVis.Find(id);
                    db.DonVis.Remove(donVi);
                    db.SaveChanges();
                    return Json(new { result = "ok" }, JsonRequestBehavior.AllowGet);

                case JsTreeOperation.MoveNode:
                    //todo: save data
                    int id3 = int.Parse(data.Id);
                    DonVi donVi3 = db.DonVis.Find(id3);
                    donVi3.parentID = int.Parse(data.ParentId);
                    db.Entry(donVi3).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { result = "ok" }, JsonRequestBehavior.AllowGet);                   

                case JsTreeOperation.RenameNode:
                    //kiểm tra có tên nào trùng không
                    if(db.DonVis.Any(x => x.ten == data.Text))
                    {
                        return Json(new { KetQua = false, ThongBao = "Bị trùng tên đơn vị" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        //todo: save data
                        int id2 = int.Parse(data.Id);
                        DonVi donVi2 = db.DonVis.Find(id2);
                        donVi2.ten = data.Text;
                        db.Entry(donVi2).State = EntityState.Modified;
                        db.SaveChanges();
                        return Json(new { KetQua = true, ThongBao = "Đã lưu vào cơ sở dữ liệu" }, JsonRequestBehavior.AllowGet);
                    }
                    

                default:
                    throw new InvalidOperationException(string.Format("{0} is not supported.", data.Operation));
            }
        }

    }
}

FirstWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">    
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    <title>QL Nhân sự Đại Dương</title>
    <!-- DAY LA TEMPLATE CUA SB-ADMIN-2 -->   
    
    <!-- Bootstrap and sb-admin-2 theme-->
    @Styles.Render("~/Content/css")

    @Styles.Render("~/Content/jqueryui")
    
    <!-- MetisMenu CSS -->
    @Styles.Render("~/vendors/metisMenu/dist")   
    
    <!-- Font Awesome -->
    @Styles.Render("~/vendors/fontawesome/css")
    @RenderSection("styles", false)  
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Phần mềm quản lý nhân sự Công ty Đại Dương</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Đổi mật khẩu</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Đăng xuất</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Trang chủ</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Danh mục<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                <li>@Html.ActionLink("Phòng ban", "Index", "jsTree")</li>
                                </li>
                                <li>
                                    <a href="morris.html">Chức vụ</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> Nhân sự<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                <li>@Html.ActionLink("Danh sách Nhân viên (modal)", "Index", "NhanViensModal")</li>
                                </li>
                                <li>
                                    <a href="buttons.html">Danh sách theo phòng ban</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Phân quyền<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Quản lý người dùng</a>
                                </li>
                                <li>
                                    <a href="#">Phân quyền</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">@RenderSection("tieude", required: false)</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        @RenderBody()
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    <!-- Bootstrap -->
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Metis Menu Plugin JavaScript -->
    @Scripts.Render("~/bundles/metisMenu/dist")

    <!-- Custom Theme Scripts -->
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.ui.datepicker-vi.js")"></script>
    <script>
        $(function () {
            $.validator.addMethod('date',
            function (value, element) {
                if (this.optional(element)) {
                    return true;
                }
                var ok = true;
                try {
                    $.datepicker.parseDate('dd/mm/yy', value);
                }
                catch (err) {
                    ok = false;
                }
                return ok;
            });
            $(".datefield").datepicker({ dateFormat: 'dd/mm/yy', changeYear: true }, $.datepicker.regional["vi"]);
        });
    </script> 
    @RenderSection("scripts", required: false)   
</body>
</html>

FirstWebApp/Views/Shared/_Layout_gentelella-master.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Đại Dương HRM</title>
    <!--ĐÂY LÀ GIAO DIEN DUA TREN GIAO DIEN gentelella-master-->
    <!-- Bootstrap and Dai Duong theme-->
    @Styles.Render("~/Content/css")
    <!-- Font Awesome -->
    @Styles.Render("~/vendors/fontawesome/css")    
    @RenderSection("styles", false)
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="index.html" class="site_title"><i class="fa fa-ship"></i> <span>Đại Dương HRM</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>Dữ liệu</h3>
                            <ul class="nav side-menu">
                                <li><a href="plain_page.html"><i class="fa fa-home"></i> Trang chủ </a></li>
                                <li>
                                    <a><i class="fa fa-edit"></i> Danh mục <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>@Html.ActionLink("Phòng ban (dạng thường)", "Index", "PhongBans")</li>
                                        <li>@Html.ActionLink("Đơn vị (dạng cây)", "Index", "jsTree")</li>
                                        <li>@Html.ActionLink("Công việc", "Index", "Dic_Job")</li>
                                        <li>@Html.ActionLink("Quốc tịch", "Index", "Dic_Nationality")</li>
                                        <li>@Html.ActionLink("Dân tộc", "Index", "Dic_Ethnic")</li>
                                        <li>@Html.ActionLink("Tôn giáo", "Index", "Dic_Religion")</li>
                                        <li>@Html.ActionLink("Quan hệ gia đình", "Index", "Dic_Relative")</li>
                                        <li>@Html.ActionLink("Học vấn", "Index", "Dic_Education")</li>
                                        <li>@Html.ActionLink("Ngoại ngữ", "Index", "Dic_Language")</li>
                                        <li>@Html.ActionLink("Tin học", "Index", "Dic_Informatic")</li>
                                        <li>@Html.ActionLink("Kỹ năng", "Index", "Dic_Skill")</li>
                                        <li>@Html.ActionLink("Bệnh viện khám chữa bệnh", "Index", "Dic_Hospital")</li>
                                        <li>@Html.ActionLink("Tỉnh thành", "Index", "Dic_Province")</li>
                                        <li>@Html.ActionLink("Trường đã học", "Index", "Dic_School")</li>
                                        <li>@Html.ActionLink("Lương tối thiểu vùng", "Index", "Dic_MinimumSalary")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-table"></i> Quản lý nhân viên <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>@Html.ActionLink("Danh sách Nhân viên", "Index", "NhanViens")</li>
                                        <li>@Html.ActionLink("Danh sách Nhân viên (modal)", "Index", "NhanViensModal")</li>
                                        <li>@Html.ActionLink("Danh sách Ứng viên", "Index", "HRM_Candidate")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-calendar-check-o"></i>Chấm công<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>@Html.ActionLink("Ký hiệu chấm công", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Danh sách thiết bị chấm công", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Danh sách Ca làm việc", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Ngày nghỉ ngày lễ", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Bảng xếp ca", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Bảng chấm công tháng", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Tổng hợp ngày công", "Index", "Home")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-area-chart"></i>Báo cáo thống kê<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>@Html.ActionLink("Danh sách Nhân viên", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Hồ sơ quá trình công tác", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Thời gian nghỉ phép trong năm", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Số tháng làm việc trong năm", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Quyết định điều động", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Danh mục hồ sơ theo thời gian", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Báo cáo lao động", "Index", "Home")</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="menu_section">
                            <h3>Hệ thống</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-users"></i> Quản lý người dùng <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>
                                            <a href="login.html">Quản lý người dùng</a>
                                        </li>
                                        <li>
                                            <a href="#">Phân quyền</a>
                                        </li>
                                    </ul>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav class="" role="navigation">
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user" style="font-size:18px; width:26px;"></i>Quốc Sỹ
                                        <span class="fa fa-angle-down"></span>
</a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li>
                                        <a href="javascript:;">  Đổi mật khẩu</a>
                                    </li>
                                    <li>
                                        <a href="login.html"><i class="fa fa-sign-out pull-right"></i> Đăng xuất</a>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    @RenderSection("tieude", required: false)
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <!-- content starts here -->
                                    @RenderBody()
                                    <!-- content ends here -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div style="text-align: center">
                    Chương trình Quản lý nhân sự công ty đóng tàu Đại Dương
                    <br />
                    Copyright ©2016 by Đại Dương
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    <!-- Bootstrap -->
    @Scripts.Render("~/bundles/bootstrap")

    <!-- Custom Theme Scripts -->
    <script src="@Url.Content("~/Scripts/dai_duong_custom.js")"></script>

    @RenderSection("scripts", required: false)
</body>
</html>